### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by astrojetson8** [Bluebie/homebridge-miio#1]
TBA

**Comment by astrojetson8** [comment]
Error: The requested platform 'XiaomiMiio' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:118:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[3/28/2017, 8:44:37 AM] Loaded plugin: homebridge-aqara
[3/28/2017, 8:44:37 AM] Registering platform 'homebridge-aqara.AqaraPlatform'
[3/28/2017, 8:44:37 AM] ---
[3/28/2017, 8:44:37 AM] Loaded plugin: homebridge-yeelight
[3/28/2017, 8:44:37 AM] Registering platform 'homebridge-yeelight.yeelight'
[3/28/2017, 8:44:37 AM] ---
[3/28/2017, 8:44:37 AM] Loaded config.json with 0 accessories and 3 platforms.
[3/28/2017, 8:44:37 AM] ---
[3/28/2017, 8:44:37 AM] Loading 3 platforms...
[3/28/2017, 8:44:37 AM] [yeelight] Initializing yeelight platform...
[3/28/2017, 8:44:37 AM] [yeelight] YeePlatform Init
[3/28/2017, 8:44:37 AM] Initializing AqaraPlatform platform...
/usr/local/lib/node_modules/homebridge/lib/api.js:118
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'XiaomiMiio' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:118:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
